import React, { useMemo, useState } from 'react';
import { BrowserRouter, Link, useLocation, useNavigate } from 'react-router-dom';
import './styles.css';

const initialStories = [
  { id: 1, title: 'The quiet art of beginning again', excerpt: 'A gentle note on making room for a new chapter, one small ritual at a time.', author: 'Maya Chen', initials: 'MC', category: 'Essays', read: '6 min read', likes: 284, date: 'Today', cover: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=900&q=80', featured: true },
  { id: 2, title: 'Letters from the edge of the map', excerpt: 'What the coast taught me about leaving, listening, and coming home.', author: 'Jon Bell', initials: 'JB', category: 'Travel', read: '8 min read', likes: 193, date: 'Yesterday', cover: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=900&q=80' },
  { id: 3, title: 'A field guide to better questions', excerpt: 'Curiosity is a practice. Here are five ways to make it part of your day.', author: 'Nora Ellis', initials: 'NE', category: 'Ideas', read: '4 min read', likes: 417, date: 'Sep 24', cover: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=900&q=80' }
];

function App() {
  const [tab, setTab] = useState('Discover');
  const [stories, setStories] = useState(initialStories);
  const [saved, setSaved] = useState([]);
  const [query, setQuery] = useState('');
  const [showComposer, setShowComposer] = useState(false);
  const [draft, setDraft] = useState({ title: '', excerpt: '', category: 'Essays' });
  const filtered = useMemo(() => stories.filter(s => `${s.title} ${s.author} ${s.category}`.toLowerCase().includes(query.toLowerCase())), [stories, query]);
  const featured = stories.find(s => s.featured) || stories[0];
  const toggleSave = id => setSaved(items => items.includes(id) ? items.filter(x => x !== id) : [...items, id]);
  const publish = e => { e.preventDefault(); if (!draft.title.trim()) return; setStories([{ ...draft, id: Date.now(), author: 'You', initials: 'YU', excerpt: draft.excerpt || 'A new story from your desk.', read: '3 min read', likes: 0, date: 'Just now', cover: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=900&q=80' }, ...stories]); setDraft({ title: '', excerpt: '', category: 'Essays' }); setShowComposer(false); setTab('Stories'); };
  return <BrowserRouter><div className="app-shell"><header className="topbar"><Link className="brand" to="/" onClick={() => setTab('Discover')}><span className="brand-mark">✦</span><span>folio</span></Link><div className="top-actions"><button className="round-btn" aria-label="Search" onClick={() => document.querySelector('.search input')?.focus()}>⌕</button><button className="avatar">YU</button></div></header><main>
    {tab === 'Discover' && <><section className="hero"><div><p className="eyebrow">A PLACE FOR YOUR WORDS</p><h1>Write what<br /><em>matters.</em></h1><p className="hero-copy">Thoughtful stories, curious minds, and a little more room to think.</p><button className="primary-btn" onClick={() => setShowComposer(true)}>Start writing <span>↗</span></button></div><div className="hero-shape"><span>“</span></div></section><div className="section-head"><div><p className="eyebrow">CURATED FOR YOU</p><h2>Featured story</h2></div><button className="text-btn" onClick={() => setTab('Stories')}>See all →</button></div><StoryCard story={featured} featured saved={saved.includes(featured.id)} onSave={toggleSave} /><div className="section-head"><div><p className="eyebrow">EXPLORE THE SHELF</p><h2>Fresh perspectives</h2></div></div><div className="chips">{['All stories', 'Essays', 'Ideas', 'Travel'].map((x, i) => <button key={x} className={i === 0 ? 'chip active' : 'chip'}>{x}</button>)}</div></>}
    {tab === 'Stories' && <><div className="page-intro"><p className="eyebrow">THE COMMUNITY</p><h1>All stories</h1><p>Find your next favorite thought.</p></div><label className="search">⌕<input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search stories or writers" /></label><div className="story-list">{filtered.map(s => <StoryCard key={s.id} story={s} saved={saved.includes(s.id)} onSave={toggleSave} />)}</div></>}
    {tab === 'Saved' && <><div className="page-intro"><p className="eyebrow">YOUR READING LIST</p><h1>Saved stories</h1><p>Keep the good ideas close.</p></div><div className="story-list">{stories.filter(s => saved.includes(s.id)).map(s => <StoryCard key={s.id} story={s} saved onSave={toggleSave} />)}{!saved.length && <div className="empty"><span>♡</span><h2>Your shelf is waiting</h2><p>Save stories here to return to them later.</p></div>}</div></>}
    {tab === 'Profile' && <><div className="profile-card"><div className="profile-avatar">YU</div><p className="eyebrow">WRITER PROFILE</p><h1>Your workspace</h1><p>Build a body of work that sounds like you.</p><div className="stats"><b>{stories.filter(s => s.author === 'You').length}<small>Published</small></b><b>{saved.length}<small>Saved</small></b><b>0<small>Followers</small></b></div></div><button className="outline-btn full" onClick={() => setShowComposer(true)}>＋ Write a new story</button></>}
  </main><nav className="bottom-nav">{[['Discover','⌂'],['Stories','▤'],['Saved','♡'],['Profile','◉']].map(([name, icon]) => <button key={name} className={tab === name ? 'nav-item active' : 'nav-item'} onClick={() => setTab(name)}><span>{icon}</span>{tab === name && <b>{name}</b>}</button>)}<button className="compose-fab" onClick={() => setShowComposer(true)} aria-label="Write">＋</button></nav>{showComposer && <div className="modal-backdrop" onClick={() => setShowComposer(false)}><form className="composer" onSubmit={publish} onClick={e => e.stopPropagation()}><button type="button" className="close" onClick={() => setShowComposer(false)}>×</button><p className="eyebrow">NEW STORY</p><h2>Put it into words.</h2><input autoFocus placeholder="Story title" value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} /><textarea placeholder="A short introduction..." value={draft.excerpt} onChange={e => setDraft({ ...draft, excerpt: e.target.value })} /><select value={draft.category} onChange={e => setDraft({ ...draft, category: e.target.value })}>{['Essays','Ideas','Travel','Poetry'].map(x => <option key={x}>{x}</option>)}</select><button className="primary-btn full">Publish story <span>↗</span></button></form></div>}</div></BrowserRouter>;
}
function StoryCard({ story, featured, saved, onSave }) { return <article className={featured ? 'story-card featured-card' : 'story-card'}><div className="story-image" style={{ backgroundImage: `url(${story.cover})` }}><span className="category-pill">{story.category}</span><button className={saved ? 'save-btn saved' : 'save-btn'} onClick={() => onSave(story.id)}>{saved ? '♥' : '♡'}</button></div><div className="story-body"><div className="author-row"><span className="author-avatar">{story.initials}</span><span><b>{story.author}</b><small>{story.date} · {story.read}</small></span></div><h3>{story.title}</h3><p>{story.excerpt}</p><div className="story-meta"><span>♡ {story.likes}</span><button className="read-btn">Read story →</button></div></div></article>; }
export default App;
