import React, { useMemo, useState } from 'react';
import { BrowserRouter, Link, useLocation, useNavigate, useParams } from 'react-router-dom';
import './styles.css';

const bikes = [
  { id: 1, name: 'Urban Explorer', type: 'City bike', price: 1299, rating: 4.9, color: 'lilac', image: 'https://images.unsplash.com/photo-1502744688674-c619d1586c9e?auto=format&fit=crop&w=900&q=85' },
  { id: 2, name: 'Road Runner Pro', type: 'Road bike', price: 1899, rating: 4.8, color: 'mint', image: 'https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?auto=format&fit=crop&w=900&q=85' },
  { id: 3, name: 'Mountain Peak', type: 'Mountain bike', price: 2199, rating: 4.7, color: 'peach', image: 'https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?auto=format&fit=crop&w=900&q=85' },
  { id: 4, name: 'Electric Flow', type: 'E-bike', price: 2499, rating: 4.9, color: 'blue', image: 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?auto=format&fit=crop&w=900&q=85' }
];

function App() {
  const [cart, setCart] = useState([]);
  const addToCart = (bike) => setCart(items => items.some(item => item.id === bike.id) ? items : [...items, bike]);
  const removeFromCart = (id) => setCart(items => items.filter(item => item.id !== id));
  return <BrowserRouter><Shell cart={cart}><Routes cart={cart} addToCart={addToCart} removeFromCart={removeFromCart} /></Shell></BrowserRouter>;
}

function Shell({ children, cart }) {
  const location = useLocation();
  const hideNav = location.pathname === '/checkout';
  return <div className="app-shell"><main>{children}</main>{!hideNav && <nav className="bottom-nav"><NavLink to="/" icon="⌂" label="Home" active={location.pathname === '/'} /><NavLink to="/shop" icon="⌕" label="Shop" active={location.pathname === '/shop'} /><NavLink to="/cart" icon="🛒" label="Cart" count={cart.length} active={location.pathname === '/cart'} /><NavLink to="/profile" icon="◉" label="Profile" active={location.pathname === '/profile'} /></nav>}</div>;
}
function NavLink({ to, icon, label, active, count }) { return <Link className={active ? 'nav-item active' : 'nav-item'} to={to}><span className="nav-icon">{icon}{count > 0 && <b className="count">{count}</b>}</span>{active && <span>{label}</span>}</Link>; }
function Header({ title, back = false }) { const navigate = useNavigate(); return <header className="topbar">{back ? <button className="circle-btn" onClick={() => navigate(-1)}>‹</button> : <div className="brand-mark">B</div>}<h1>{title}</h1><Link className="circle-btn" to="/cart">🛒</Link></header>; }
function Routes({ cart, addToCart, removeFromCart }) { const path = useLocation().pathname; if (path === '/cart') return <Cart cart={cart} removeFromCart={removeFromCart} />; if (path === '/checkout') return <Checkout cart={cart} />; if (path === '/profile') return <Profile />; if (path === '/shop') return <Shop addToCart={addToCart} />; if (path.startsWith('/product/')) return <Product addToCart={addToCart} />; return <Home addToCart={addToCart} />; }
function Home({ addToCart }) { return <><Header title="Bikehaus" /><section className="hero"><div><span className="eyebrow">RIDE YOUR WAY</span><h2>Find your<br /><em>perfect ride.</em></h2><p>Explore bikes made for every kind of adventure.</p><Link className="primary-btn small" to="/shop">Explore bikes <span>→</span></Link></div><div className="hero-bike">🚲</div></section><SectionTitle title="Popular bikes" action="See all" to="/shop" /><div className="horizontal-list">{bikes.slice(0, 2).map(bike => <BikeCard key={bike.id} bike={bike} addToCart={addToCart} />)}</div><SectionTitle title="Shop by category" /><div className="categories"><Category icon="🚴" label="Road" /><Category icon="🏔️" label="Mountain" /><Category icon="⚡" label="E-bike" /><Category icon="🏙️" label="City" /></div></>; }
function SectionTitle({ title, action, to }) { return <div className="section-title"><h2>{title}</h2>{action && <Link to={to}>{action} →</Link>}</div>; }
function Category({ icon, label }) { return <Link to="/shop" className="category"><span>{icon}</span><small>{label}</small></Link>; }
function BikeCard({ bike, addToCart }) { return <article className="bike-card"><Link to={`/product/${bike.id}`}><div className={`bike-image ${bike.color}`}><img src={bike.image} alt={bike.name} /><button className="heart" onClick={(e) => e.preventDefault()}>♡</button></div></Link><div className="bike-info"><div><h3>{bike.name}</h3><p>{bike.type}</p><strong>${bike.price.toLocaleString()}</strong></div><button className="add-btn" onClick={() => addToCart(bike)}>+</button></div><span className="rating">★ {bike.rating}</span></article>; }
function Shop({ addToCart }) { const [query, setQuery] = useState(''); const filtered = useMemo(() => bikes.filter(b => b.name.toLowerCase().includes(query.toLowerCase())), [query]); return <><Header title="Shop bikes" back /><div className="search"><span>⌕</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search bikes" /><span>☷</span></div><div className="filter-row"><button className="filter active">All bikes</button><button className="filter">Road</button><button className="filter">Mountain</button><button className="filter">E-bike</button></div><div className="shop-grid">{filtered.map(bike => <BikeCard key={bike.id} bike={bike} addToCart={addToCart} />)}</div></>; }
function Product({ addToCart }) { const { id } = useParams(); const bike = bikes.find(item => item.id === Number(id)) || bikes[0]; return <><Header title="Bike details" back /><div className="product-hero"><img src={bike.image} alt={bike.name} /><button className="heart large">♡</button></div><div className="product-heading"><div><span className="eyebrow">{bike.type.toUpperCase()}</span><h2>{bike.name}</h2></div><strong>${bike.price.toLocaleString()}</strong></div><div className="rating-line"><span className="rating solid">★ {bike.rating}</span><span>128 reviews</span><span className="dot">•</span><span>Free delivery</span></div><p className="description">Designed for smooth everyday rides, the {bike.name} combines lightweight comfort with confident performance. Built to make every journey feel effortless.</p><div className="specs"><Spec icon="◈" label="Frame" value="Carbon" /><Spec icon="◌" label="Weight" value="8.4 kg" /><Spec icon="⚙" label="Gears" value="18 speed" /></div><button className="primary-btn full" onClick={() => addToCart(bike)}>Add to cart <span>→</span></button></>; }
function Spec({ icon, label, value }) { return <div><span>{icon}</span><small>{label}</small><b>{value}</b></div>; }
function Cart({ cart, removeFromCart }) { const total = cart.reduce((sum, item) => sum + item.price, 0); return <><Header title="My cart" back />{cart.length === 0 ? <EmptyCart /> : <><div className="cart-list">{cart.map(item => <div className="cart-item" key={item.id}><img src={item.image} alt={item.name} /><div><h3>{item.name}</h3><p>{item.type}</p><strong>${item.price.toLocaleString()}</strong></div><button onClick={() => removeFromCart(item.id)}>×</button></div>)}</div><div className="summary"><div><span>Subtotal</span><b>${total.toLocaleString()}</b></div><div><span>Delivery</span><b className="green">Free</b></div><hr /><div className="total"><span>Total</span><b>${total.toLocaleString()}</b></div><Link className="primary-btn full" to="/checkout">Continue to checkout <span>→</span></Link></div></>}</>; }
function EmptyCart() { return <div className="empty"><div>🛒</div><h2>Your cart is empty</h2><p>Find a bike that makes you want to ride.</p><Link className="primary-btn" to="/shop">Explore bikes</Link></div>; }
function Checkout({ cart }) { const total = cart.reduce((sum, item) => sum + item.price, 0); return <><Header title="Checkout" back /><div className="checkout"><h2>Delivery details</h2><label>Full name<input placeholder="Alex Morgan" /></label><label>Delivery address<input placeholder="24 Oak Street, Portland" /></label><label>Payment method<div className="payment"><span>💳</span>•••• 4242 <b>✓</b></div></label><div className="checkout-total"><span>Total to pay</span><b>${total.toLocaleString()}</b></div><button className="primary-btn full" onClick={() => alert('Thanks! Your order has been placed.')}>Place order <span>→</span></button></div></>; }
function Profile() { return <><Header title="Profile" /><div className="profile-head"><div className="avatar">AM</div><h2>Alex Morgan</h2><p>alex.morgan@email.com</p></div><div className="profile-menu"><Menu icon="♡" label="Saved bikes" /><Menu icon="▣" label="Order history" /><Menu icon="⌖" label="Delivery addresses" /><Menu icon="⚙" label="Settings" /></div><div className="member"><span>✦</span><div><b>Ride Club member</b><p>Earn points with every purchase</p></div><span>→</span></div></>; }
function Menu({ icon, label }) { return <button className="menu-row"><span>{icon}</span>{label}<b>›</b></button>; }
export default App;
