import React, { useMemo, useState } from 'react';
import { BrowserRouter, Link, useLocation, useNavigate, useParams } from 'react-router-dom';
import './styles.css';

const bikes = [
  { id: 1, name: 'Aero City 1', type: 'City bike', price: 1299, rating: 4.9, reviews: 128, color: 'lilac', image: 'https://images.unsplash.com/photo-1502744688674-c619d1586c9e?auto=format&fit=crop&w=1000&q=85', description: 'A smooth, confident city ride designed for every day.', specs: [['Frame', 'Aluminium'], ['Gears', '8 speed'], ['Weight', '11.2 kg']] },
  { id: 2, name: 'Road Runner S', type: 'Road bike', price: 1899, rating: 4.8, reviews: 96, color: 'mint', image: 'https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?auto=format&fit=crop&w=1000&q=85', description: 'Lightweight speed for long roads and fast weekend escapes.', specs: [['Frame', 'Carbon'], ['Gears', '22 speed'], ['Weight', '8.4 kg']] },
  { id: 3, name: 'Summit X', type: 'Mountain bike', price: 2199, rating: 4.7, reviews: 84, color: 'peach', image: 'https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?auto=format&fit=crop&w=1000&q=85', description: 'Trail-ready control with confidence over every climb.', specs: [['Frame', 'Aluminium'], ['Gears', '12 speed'], ['Weight', '12.8 kg']] },
  { id: 4, name: 'Volt Commuter', type: 'E-bike', price: 2499, rating: 4.9, reviews: 152, color: 'blue', image: 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?auto=format&fit=crop&w=1000&q=85', description: 'Effortless electric power for a better daily commute.', specs: [['Range', '80 km'], ['Assist', '25 km/h'], ['Weight', '18.1 kg']] }
];

const categories = [{ icon: '⌁', label: 'All bikes', value: 'All' }, { icon: '◒', label: 'City', value: 'City bike' }, { icon: '↗', label: 'Road', value: 'Road bike' }, { icon: '⌁', label: 'Mountain', value: 'Mountain bike' }, { icon: '⚡', label: 'E-bike', value: 'E-bike' }];
const money = value => `$${value.toLocaleString()}`;

function App() {
  const [cart, setCart] = useState([]);
  const [favorites, setFavorites] = useState([]);
  const addToCart = bike => setCart(items => items.some(item => item.id === bike.id) ? items : [...items, bike]);
  const removeFromCart = id => setCart(items => items.filter(item => item.id !== id));
  const toggleFavorite = id => setFavorites(items => items.includes(id) ? items.filter(item => item !== id) : [...items, id]);
  return <BrowserRouter><Shell cartCount={cart.length}><Routes cart={cart} addToCart={addToCart} removeFromCart={removeFromCart} favorites={favorites} toggleFavorite={toggleFavorite} /></Shell></BrowserRouter>;
}

function Shell({ children, cartCount }) {
  const location = useLocation();
  const hidden = location.pathname === '/checkout';
  return <div className="app-shell"><main>{children}</main>{!hidden && <nav className="bottom-nav"><NavItem to="/" icon="⌂" label="Home" active={location.pathname === '/'} /><NavItem to="/shop" icon="⌕" label="Discover" active={location.pathname === '/shop'} /><NavItem to="/cart" icon="▱" label="Bag" active={location.pathname === '/cart'} count={cartCount} /><NavItem to="/profile" icon="◉" label="Profile" active={location.pathname === '/profile'} /></nav>}</div>;
}
function NavItem({ to, icon, label, active, count }) { return <Link className={`nav-item ${active ? 'active' : ''}`} to={to}><span className="nav-icon">{icon}{count > 0 && <b className="count">{count}</b>}</span><small>{label}</small></Link>; }
function Header({ title, back = false, action }) { const navigate = useNavigate(); return <header className="topbar">{back ? <button className="icon-btn" onClick={() => navigate(-1)} aria-label="Go back">←</button> : <Link to="/" className="brand"><span className="brand-mark">B</span><span>BIKEHAUS</span></Link>}<h1>{title}</h1>{action || <div className="topbar-spacer" />}</header>; }
function Routes(props) { const path = useLocation().pathname; if (path === '/shop') return <Shop {...props} />; if (path === '/cart') return <Cart {...props} />; if (path === '/checkout') return <Checkout cart={props.cart} />; if (path === '/profile') return <Profile />; if (path.startsWith('/product/')) return <Product {...props} />; return <Home {...props} />; }

function Home({ addToCart, favorites, toggleFavorite }) {
  return <><Header title="" action={<Link to="/profile" className="avatar">AM</Link>} /><section className="welcome"><div><p className="eyebrow">SATURDAY, SEPTEMBER 26</p><h1>Ride into<br /><em>your next chapter.</em></h1><p className="welcome-copy">Curated bikes for people who would rather be out there.</p><Link className="primary-btn" to="/shop">Explore collection <span>↗</span></Link></div><div className="hero-orbit"><span>NEW<br /><b>2026</b></span></div></section><section className="section-block"><SectionTitle title="Browse by style" action="See all" to="/shop" /><div className="category-row">{categories.slice(1).map(category => <Link to={`/shop?type=${encodeURIComponent(category.value)}`} className="category" key={category.value}><span>{category.icon}</span><small>{category.label}</small></Link>)}</div></section><section className="section-block"><SectionTitle title="Trending now" action="View all" to="/shop" /><div className="bike-grid">{bikes.slice(0, 2).map(bike => <BikeCard key={bike.id} bike={bike} addToCart={addToCart} favorite={favorites.includes(bike.id)} toggleFavorite={toggleFavorite} />)}</div></section></>;
}
function SectionTitle({ title, action, to }) { return <div className="section-title"><h2>{title}</h2><Link to={to}>{action} <span>→</span></Link></div>; }
function BikeCard({ bike, addToCart, favorite, toggleFavorite }) { return <article className="bike-card"><button className={`heart ${favorite ? 'saved' : ''}`} onClick={() => toggleFavorite(bike.id)} aria-label="Save bike">{favorite ? '♥' : '♡'}</button><Link to={`/product/${bike.id}`}><div className={`bike-image ${bike.color}`}><img src={bike.image} alt={bike.name} /></div><div className="bike-info"><div><p>{bike.type}</p><h3>{bike.name}</h3></div><strong>{money(bike.price)}</strong></div><div className="rating"><span>★</span> {bike.rating} <i>·</i> {bike.reviews} reviews</div></Link><button className="quick-add" onClick={() => addToCart(bike)}>+ Add to bag</button></article>; }
function Shop({ addToCart, favorites, toggleFavorite }) { const [query, setQuery] = useState(''); const [type, setType] = useState('All'); const params = new URLSearchParams(useLocation().search); const initialType = params.get('type'); const activeType = type === 'All' && initialType ? initialType : type; const filtered = useMemo(() => bikes.filter(b => (activeType === 'All' || b.type === activeType) && `${b.name} ${b.type}`.toLowerCase().includes(query.toLowerCase())), [query, activeType]); return <><Header title="Discover" action={<Link to="/cart" className="header-bag">▱</Link>} /><div className="shop-intro"><p className="eyebrow">THE COLLECTION</p><h2>Find your<br /><em>perfect ride.</em></h2></div><label className="search"><span>⌕</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search bikes, styles..." /></label><div className="filter-scroll">{categories.map(c => <button className={activeType === c.value ? 'filter active' : 'filter'} onClick={() => setType(c.value)} key={c.value}>{c.label}</button>)}</div><div className="results-head"><span>{filtered.length} bikes</span><button>Sort by <b>Featured⌄</b></button></div><div className="bike-grid shop-grid">{filtered.map(bike => <BikeCard key={bike.id} bike={bike} addToCart={addToCart} favorite={favorites.includes(bike.id)} toggleFavorite={toggleFavorite} />)}</div>{filtered.length === 0 && <div className="empty"><div>⌕</div><h2>No bikes found</h2><p>Try another search or category.</p></div>}</>; }
function Product({ addToCart, favorites, toggleFavorite }) { const { id } = useParams(); const bike = bikes.find(item => item.id === Number(id)) || bikes[0]; return <><Header title="Bike details" back action={<button className={`icon-btn heart-detail ${favorites.includes(bike.id) ? 'saved' : ''}`} onClick={() => toggleFavorite(bike.id)}>{favorites.includes(bike.id) ? '♥' : '♡'}</button>} /><div className={`product-hero ${bike.color}`}><img src={bike.image} alt={bike.name} /></div><div className="product-copy"><p className="eyebrow">{bike.type.toUpperCase()}</p><div className="product-title"><h2>{bike.name}</h2><strong>{money(bike.price)}</strong></div><div className="rating"><span>★</span> {bike.rating} <i>·</i> {bike.reviews} reviews</div><p className="description">{bike.description}</p><div className="spec-grid">{bike.specs.map(([label, value]) => <div key={label}><small>{label}</small><b>{value}</b></div>)}</div><button className="primary-btn full" onClick={() => addToCart(bike)}>Add to bag <span>→</span></button></div></>; }
function Cart({ cart, removeFromCart }) { const total = cart.reduce((sum, item) => sum + item.price, 0); return <><Header title="Your bag" back /><div className="page-heading"><p className="eyebrow">READY WHEN YOU ARE</p><h2>{cart.length ? `${cart.length} ${cart.length === 1 ? 'bike' : 'bikes'} selected` : 'Your bag is empty'}</h2></div>{cart.length === 0 ? <div className="empty"><div>▱</div><p>Find a bike that makes you want to ride.</p><Link className="primary-btn" to="/shop">Explore bikes <span>↗</span></Link></div> : <><div className="cart-list">{cart.map(item => <div className="cart-item" key={item.id}><img src={item.image} alt="" /><div><small>{item.type}</small><h3>{item.name}</h3><b>{money(item.price)}</b></div><button onClick={() => removeFromCart(item.id)} aria-label="Remove">×</button></div>)}</div><div className="summary"><div><span>Subtotal</span><b>{money(total)}</b></div><div><span>Delivery</span><b className="green">Free</b></div><hr /><div className="total"><span>Total</span><b>{money(total)}</b></div><Link className="primary-btn full" to="/checkout">Checkout <span>→</span></Link></div></>}</>; }
function Checkout({ cart }) { const total = cart.reduce((sum, item) => sum + item.price, 0); return <><Header title="Checkout" back /><div className="checkout"><p className="eyebrow">ALMOST THERE</p><h2>Make it yours.</h2><label>Full name<input placeholder="Alex Morgan" /></label><label>Email address<input placeholder="alex@example.com" type="email" /></label><label>Delivery address<input placeholder="123 Ride Street" /></label><div className="payment"><span>▣</span><div><b>•••• 4242</b><small>Visa · expires 08/28</small></div><button>Change</button></div><div className="checkout-total"><span>Total today</span><b>{money(total)}</b></div><button className="primary-btn full" onClick={() => alert('Order placed — happy riding!')}>Place order <span>→</span></button></div></>; }
function Profile() { return <><Header title="Profile" /><div className="profile-head"><div className="profile-avatar">AM</div><p className="eyebrow">WELCOME BACK</p><h2>Alex Morgan</h2><p>alex.morgan@email.com</p></div><div className="profile-card"><Menu icon="⌁" label="My orders" /><Menu icon="♡" label="Saved bikes" /><Menu icon="◌" label="Ride preferences" /><Menu icon="⚙" label="Settings" /></div><div className="member-card"><span>BIKEHAUS MEMBER</span><b>RIDE MORE. WORRY LESS.</b><small>Member since 2024 · 240 points</small></div></>; }
function Menu({ icon, label }) { return <button className="menu-row"><span>{icon}</span>{label}<b>›</b></button>; }
export default App;
